# Generated by Django 4.2.7 on 2023-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_email", models.EmailField(max_length=254, unique=True)),
                ("owner_name", models.CharField(max_length=20)),
                ("pet_name", models.CharField(max_length=20)),
                ("pet_breed", models.CharField(max_length=20)),
            ],
        ),
    ]
